import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Add this
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'package:safestep/pages/splash_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // Only initialize if no apps exist
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    }
    debugPrint("✅ Firebase Initialized Successfully");
  } on FirebaseException catch (e) {
    if (e.code == 'duplicate-app') {
      debugPrint("ℹ️ Firebase already initialized (Duplicate App)");
    } else {
      debugPrint("❌ Firebase Error: $e");
    }
  } catch (e) {
    debugPrint("❌ Unknown Error: $e");
  }

  runApp(const SafeStepApp());
}

class SafeStepApp extends StatelessWidget {
  const SafeStepApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: SplashScreen(),
    );
  }
}